sudo: required

services:
  - docker

install:
  - docker build -t docker-jenkins-config:travis .
  - docker run -d --name jenkins --env-file ./env.list docker-jenkins-config:travis

script:
 - docker ps | grep -q jenkins
